### ISSUE TITLE
NextJS 관련 프로젝트 세팅 작업

### ISSUE THREAD

**Issue by jgjgill** [prgrms-web-devcourse/React-Playground-Study#20]
## NextJS 관련 프로젝트 세팅 작업을 진행합니다.

함께 할 수 있는 미니 프로젝트로 팀 블로그를 만들어보려고 합니다!
이를 위한 기본 세팅 작업을 시작하겠습니다.

### 해야할 일
- [x] NextJS 시작 template 내 안쓰는 파일 제거
- [x] eslint, prettier, typescript, 스타일 라이브러리 등 기본적인 세팅 작업

작업하실 분은 Assignees에 등록해주세요..!
더 추가할 부분이 있으면 편하게 이야기해주세요!

감사합니다..! 🙇‍♂️

**Comment by HongGunWoo** [comment]
초기 설정 했습니다! pr 에서 확인 부탁드려요!
