### ISSUE TITLE
todo list 렌더링 하기(feat: 오류 해결) + github 알게된 내용

### ISSUE THREAD

**Issue by jkea1** [prgrms-web-devcourse/React-Playground-Study#25]
### submit event를 받는 e는 어떤 타입을 정해줘야 할까?

https://stackoverflow.com/questions/61265736/parameter-e-implicitly-has-an-any-type-react-typescript

### 해결 방법
`const handleAdd = (e: React.FormEvent) => {
  e.preventDefault()
}`

### 해결 방법
> 인자를 인터페이스 Props로 검사를 해줬는데 인자검사를 해주라는 오류가 뜬다. 
> `React.FC<Props>` 해서 한번 더 검사를 해주었다!

`const handleAdd = (e: React.FormEvent) => {
  e.preventDefault()
}`

## 🧐 깃헙 관련 궁금한 점

- [x] #28

- [x] 개인 공부하는 걸 올리는 경우에는 어떤 방법으로 깃헙에 올리는게 좋을까요?

**Comment by jgjgill** [comment]
스택오버플로우 링크가 잘못 지정되어 있는 것 같네요..!

## 첫 번째 내용

저같은 경우 `onSubmit`, `onChange`같은 이벤트 관련 타입은 에러 표시를 통해 확인하는 편입니다..!
`const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {e.preventDefault()}`

<img width="1440" alt="스크린샷 2023-08-21 오후 11 58 19" src="https://github.com/prgrms-web-devcourse/React-Playground-Study/assets/79239852/ec12eaf5-f7da-4ff0-ba73-b9170b117f41">

## 두 번째 내용

`const TodoList: React.FC = ({ todos, setTodos }: Props) => { ... }` 이 코드는 `React.FC`를 없애고 똑같이 동작할 것 같아요!
`const TodoList = ({ todos, setTodos }: Props) => { ... }`

**Comment by jkea1** [comment]
에러 표시를 통해 확인하는 편이시군요! 혹시나 외워야 하나 걱정했는데 다행입니다! 알려주셔서 감사합니다! 👍
