### ISSUE TITLE
한 브렌치로는 merge 전까지 PR을 한 번 밖에 날리지 못하는군요. 실제 프로젝트에서는 자신의 브렌치가 하나일텐데 어떻게 진행하는 걸까요?

### ISSUE THREAD

**Issue by jkea1** [prgrms-web-devcourse/React-Playground-Study#28]
[깃허브로 그룹프로젝트 하는 법](https://youtu.be/tkkbYCajCjM)
오늘 이거 보고 한번 정리해 보려 합니다~ 😁

**Comment by jgjgill** [comment]
저는 깃이나 깃허브 관련된 부분은 처음이 어렵지 막상하면 별거 아니라는 느낌을 많이 받더라구요!!
반복적인 것도 많구요..!
학습하시고 마음껏 적용해보시길 바랍니다! 🙇‍♂️

**Comment by jkea1** [comment]
맞아요~ 종길님~ 처음이 어렵지 반복해서 사용해보면 익숙해지겠죠?? 
노션에 정리한 내용 공유합니다! 

[🖇️ 깃헙 이용해서 그룹 프로젝트 하기](https://www.notion.so/0a2e4dba9d6f4a6ead6fbed6bd77604d?pvs=4)

다음에는 docs에도 정리해 볼게요! 😁

> develop 브렌치를 만들어야 겠다고 생각했고, Projects 안의 Board를 팀원들과 적극 사용하면 프로젝트 일정을 효과적으로 정리 할 수 있을 것 같습니다!
