### ISSUE TITLE
깃헙 이용해서 그룹 프로젝트 하는 법

### ISSUE THREAD

**Issue by jkea1** [prgrms-web-devcourse/React-Playground-Study#30]
댓글에서 이슈를 또 생성이 가능하네요? 신기한 깃헙 세계...
노션에 정리한 내용 공유합니다! 

[🖇️ 깃헙 이용해서 그룹 프로젝트 하기](https://www.notion.so/0a2e4dba9d6f4a6ead6fbed6bd77604d?pvs=4)

유튜브 영상에 잘 정리돼 있어서 영상 링크도 첨부 합니다!

[youtube 영상](https://youtu.be/tkkbYCajCjM)

> develop 브렌치를 만들어야 겠다고 생각했고, Projects 안의 Board를 팀원들과 적극 사용하면 프로젝트 일정을 효과적으로 정리 할 수 있을 것 같습니다!

_Originally posted by @jkea1 in https://github.com/prgrms-web-devcourse/React-Playground-Study/issues/28#issuecomment-1687675407_

**Comment by backward99** [comment]
Projects에 유용한게 많네요..! 영상에는 간단한 내용으로 충돌을 다뤘는데 내용이 많아지면 얼마나 복잡해질지...끔찍하네요..
좋은 영상 추천 감사합니다! 노션 내용은 공유가 풀린것 같기도합니다!(저만 그럴수도..)

**Comment by jkea1** [comment]
앗 노션 링크에 접속이 안되나요?? [여기로](https://repeated-paprika-d0d.notion.site/0a2e4dba9d6f4a6ead6fbed6bd77604d?pvs=4) 한번 더 확인해 보시겠어요?
