### ISSUE TITLE
원격 브렌치 불러오는법

### ISSUE THREAD

**Issue by jkea1** [prgrms-web-devcourse/React-Playground-Study#44]
### 원격브렌치 불러오는법 🧐
처음에 플레이그라운드 레포를 clone 받아올때 *`git clone -b 내브렌치 --single-branch url주소`* 로 내 브런치만 불러와서 일까? docs 브런치로 바꾸기 위해 *` git branch -a `* 로 로컬, 원격 브렌치를 확인해 본 결과 내 로컬, 원격 브렌치 이렇게 두개 밖에 확인이 안 됐다. 
최종  *`git clone -b docs --single-branch url주소`* 해서 docs 브렌치를 하나 더 따 와서 해결했기는 한데 다른 방법이 있을까?

**Comment by jgjgill** [comment]
저같은 경우 브랜치만 클론하는 방식이 아닌 저장소를 클론하는 방식으로 하는데요!!
저장소를 클론하고 원격 저장소 브랜치를 확인합니다! `git branch -r`
그리고 로컬에서 원격 저장소 브랜치를 생성하고 내용을 가져오는 방식으로 하는 것 같네요!
`git checkout -b 원격저장소 브랜치 이름` -> `git pull 원격 저장소 이름 원격 저장소 브랜치 이름`
