### ISSUE TITLE
useCallback 사용 관련 질문!

### ISSUE THREAD

**Issue by jkea1** [prgrms-web-devcourse/React-Playground-Study#49]
## 질문 내용
todolist 만들기 토이프로젝트에서 handleAdd 기능 리팩토링을 했는데 useCallback에 대한 이해가 부족해서 그런지 handleAdd 함수 안 콘솔 부분의 todos가 왜 빈 배열로 출력이 되는지 모르겠습니다. 기능은 잘 하고 있는데.. 🧐
[handleAdd 리팩토링 내용 (App.tsx 파일을 봐주세요.)](https://github.com/prgrms-web-devcourse/React-Playground-Study/commit/4b85fba02af2a489b8e7fbe13ec37f7236326538)

+ 저번에 했던 PR을 main에 merge를 안해서 한꺼번에 올라가 버렸네요ㅜㅜ 최근 refactor 커밋 내용만 봐주시면 됩니다.

**Comment by jkea1** [comment]
네.. 그래서 임시로 useEffect 만들어서 찍어봤는데 여기서는 제대로 todo가 들어간 todos를 확인 할 수 있더라구요? 그런데 왜 useCallback 안에서는 todos가 빈 배열일까요?? 🧐

**Comment by jgjgill** [comment]
`useCallback` 때문에 빈배열이 나왔다고는 생각하지 않습니다..!
저는 리액트 렌더링과 관련된 부분이라고 생각되는데요!! 지난번 지호님이 공유해주신 내용과도 관련있다고 느껴집니다!
`handleAdd` 내부에서 진경님이 생각하는 콘솔을 보려면 `setTodos((prev) => [...prev, { id: Date.now(), todo, isDone: false }])`
이렇게 하시면 될 것 같습니다.

함수형 업데이트라고 표현하는 것 같네요. `batching`이라는 키워드로 알아봐도 괜찮을 것 같습니다.

**Comment by jkea1** [comment]
오~ 이게 그렇게 연결이 되군요! 다시 생각해보고 질문 드리겠습니다! 종길님 늦은 시간까지 수고가 많으십니다! 감사합니다! 😁👍

**Comment by jkea1** [comment]
setState는 동기적 함수죠!  리렌더링 되기 전까지 todos가 참고하는 클로저 내부 값이 실제로 변경되지 않았기 때문에 업데이트된  todos 값이 콘솔에 찍히지 않았던 거네요! 지호님 글 보고 한번 더 정리하고 갑니다! 👍
